### ISSUE TITLE
When closing child window, Gwen can get confused about the parent window ID

### ISSUE THREAD

**Issue by inkbleed** [gwen-interpreter/gwen-web#37]
Hi,

Firstly, Gwen is an amazing tool! Thanks a ton for putting it up online. 

The issue is that, when using the command "I close the child window", Gwen tracks the incorrect parent id, if you're running Gwen in batch mode and the test is not the first feature. This causes gwen to crash when attempting to return to the parent. 

If the step appears in the first script in a batch (or if you're just running one feature), then it works fine. Switching to parent also works fine. In the logs below, you can see Gwen correctly identifies the parent window id when switching from child to parent, however incorrectly identifies it when _closing_ the child window. 

My guess is that it's caching the parent window id of the window that opens on the very first feature, when it should be updating the parent window id at the start of each feature. 

INFO - [~0ms] Passed Step: Given I am on the registration page
INFO - Evaluating Step: When I click the privacy policy link
INFO - [302ms] Passed Step: When I click the privacy policy link
INFO - Evaluating Step: And I switch to the child window
INFO - Switching to child window ({a234d6cb-6e70-4d04-b1c7-d73caaf59876})
INFO - [80ms] Passed Step: And I switch to the child window
INFO - Evaluating Step: Then I wait until "($('h2').text() == 'Privacy Policy')"
INFO - Waiting until ($('h2').text() == 'Privacy Policy')
INFO - [1s 025ms] Passed Step: Then I wait until "($('h2').text() == 'Privacy Policy')"
INFO - Evaluating Step: And I switch to the parent window
INFO - Switching to parent window ({**6c145166-cc89-4611-bfc2-e6ca43987260**})
INFO - [16ms] Passed Step: And I switch to the parent window
INFO - Evaluating Step: And I close the child window
INFO - Closing child window ({a234d6cb-6e70-4d04-b1c7-d73caaf59876})
INFO - Switching to parent window ({**ab635c96-b73f-4e9f-b04f-a32f410e503a**})
INFO - Closing environment context
INFO - Closing browser session
org.openqa.selenium.NoSuchWindowException: Window not found. The browser window may have been closed.
Command duration or timeout: 5 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'zubzub', ip: '10.1.1.203', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.8.0, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 978233a0-aea9-422a-8506-034fa9f5a084
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
        at org.openqa.selenium.firefox.FirefoxDriver.getScreenshotAs(FirefoxDriver.java:341)
        at gwen.web.DriverManager$class.captureScreenshot(DriverManager.scala:177)
        at gwen.web.WebEnvContext.captureScreenshot(WebEnvContext.scala:59)
        at gwen.web.WebEnvContext$$anonfun$addErrorAttachments$1.apply$mcV$sp(WebEnvContext.scala:208)
        at gwen.web.WebEnvContext$$anonfun$addErrorAttachments$1.apply(WebEnvContext.scala:208)
        at gwen.web.WebEnvContext$$anonfun$addErrorAttachments$1.apply(WebEnvContext.scala:208)
        at gwen.eval.ExecutionContext$class.execute(ExecutionContext.scala:33)
        at gwen.eval.EnvContext.execute(EnvContext.scala:51)
        at gwen.web.WebEnvContext.addErrorAttachments(WebEnvContext.scala:208)
        at gwen.eval.EnvContext.fail(EnvContext.scala:189)
        at gwen.eval.EvalEngine$class.doEvaluate(EvalEngine.scala:110)
        at gwen.eval.EvalEngine$class.evaluateStep(EvalEngine.scala:77)
        at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
        at gwen.eval.EvalEngine$$anonfun$evaluateSteps$1.apply(EvalEngine.scala:140)
        at gwen.eval.EvalEngine$$anonfun$evaluateSteps$1.apply(EvalEngine.scala:137)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at gwen.eval.EvalEngine$class.evaluateSteps(EvalEngine.scala:136)
        at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
        at gwen.eval.GwenInterpreter.gwen$eval$GwenInterpreter$$evaluateScenario(GwenInterpreter.scala:203)
        at gwen.eval.GwenInterpreter$$anonfun$5.apply(GwenInterpreter.scala:167)
        at gwen.eval.GwenInterpreter$$anonfun$5.apply(GwenInterpreter.scala:150)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at gwen.eval.GwenInterpreter.gwen$eval$GwenInterpreter$$evaluateFeature(GwenInterpreter.scala:149)
        at gwen.eval.GwenInterpreter$$anonfun$interpretFeature$2.apply(GwenInterpreter.scala:121)
        at gwen.eval.GwenInterpreter$$anonfun$interpretFeature$2.apply(GwenInterpreter.scala:111)
        at scala.Option.map(Option.scala:146)
        at gwen.eval.GwenInterpreter.interpretFeature(GwenInterpreter.scala:111)
        at gwen.eval.GwenLauncher.gwen$eval$GwenLauncher$$evaluateUnit(GwenLauncher.scala:155)
        at gwen.eval.GwenLauncher$$anonfun$executeFeatureUnits$4.apply(GwenLauncher.scala:124)
        at gwen.eval.GwenLauncher$$anonfun$executeFeatureUnits$4.apply(GwenLauncher.scala:120)
        at scala.collection.immutable.Stream.foldLeft(Stream.scala:610)
        at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:120)
        at gwen.eval.GwenLauncher.run(GwenLauncher.scala:58)
        at gwen.eval.GwenApp.run(GwenApp.scala:50)
        at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:34)
        at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:29)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at gwen.eval.GwenApp.main(GwenApp.scala:29)
        at gwen.web.WebInterpreter.main(WebIntepreter.scala)
Caused by: org.openqa.selenium.NoSuchWindowException: Window not found. The browser window may have been closed.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'zubzub', ip: '10.1.1.203', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
        at <anonymous class>.nsCommandProcessor.prototype.execute(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12719)
        at <anonymous class>.Dispatcher.executeAs/<(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9558)
        at <anonymous class>.Resource.prototype.handle(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9705)
        at <anonymous class>.Dispatcher.prototype.dispatch(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9652)
        at <anonymous class>.WebDriverServer/<.handle(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:12517)
        at <anonymous class>.createHandlerFunc/<(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
        at <anonymous class>.ServerHandler.prototype.handleResponse(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
        at <anonymous class>.Connection.prototype.process(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
        at <anonymous class>.RequestReader.prototype._handleResponse(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
        at <anonymous class>.RequestReader.prototype._processBody(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
        at <anonymous class>.RequestReader.prototype.onInputStreamReady(file:///C:/Users/inkbleed/AppData/Local/Temp/anonymous4895535360069169933webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1393)

**Comment by bjuric** [comment]
Hi,

Thank you for raising this one.  I've built a snapshot containing a change that resets the window tracking for each feature execution.  Please retest using the build below and let me know if the problem persists.

[gwen-web-2.4.0-1-ga0c02f5-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.4.0-1-ga0c02f5-SNAPSHOT/gwen-web-2.4.0-1-ga0c02f5-SNAPSHOT.zip)

**Comment by inkbleed** [comment]
[gwen_crash.txt](https://github.com/gwen-interpreter/gwen-web/files/945831/gwen_crash.txt)

Unfortunately this version isn't running....on firefox, chrome and IE it's just opening 2 blank windows then crashing. See attached. 

Cheers for the quick response though!

**Comment by bjuric** [comment]
Ok, please provide following info..
- The Gwen version you were using when you reported this error
- Your firefox version
- Your firefox native driver and version
Also, try updating the browsers and native drivers in your environment. This snapshot is built on the latest selenium 3.3.1

**Comment by bjuric** [comment]
Looking at your error traces, it appears that you are using selenium v2.53.1 with older browsers.  If you really need to stay with this, you can still use the latest Gwen build (including the snapshot provided here) and have it [switch to that selenium version](https://github.com/gwen-interpreter/gwen-web/wiki/Runtime-Settings#changing-the-selenium-version) instead of the latest bundled one as follows:

1. Download and extract [selenium-java-2.53.1.zip](http://selenium-release.storage.googleapis.com/2.53/selenium-java-2.53.1.zip) to a location on your drive
2. Set the SELENIUM_HOME environment variable on your system to point to this location
3. Run Gwen again (using the snapshot build provided here in your case)

Otherwise, please provide more info so I can help you.

**Comment by inkbleed** [comment]
Hi,

Thanks for that info. I'm sure we'll be fine to update to the latest...I'll do this on Monday and try it out, and let you know. 

Thanks a lot!

**Comment by inkbleed** [comment]
Sorry about this, but I'm not having any luck getting the snapshot version working!

I've updated to the latest version of Java, and am using Firefox ESR v45.9.0, and geckodriver v0.16.0 which appears to be the latest. 

I originally raised the ticket on Gwen 1.8.0, but am retesting with your latest snapshot. 

On the 2.4.0 snapshot attached, Gwen is opening a new empty firefox window then freezing. If I manually close the window gwen opens a second empty one, and if I close that it crashes. Logs are using the flood.io example. 

The full log is here:
[crash_log.txt](https://github.com/gwen-interpreter/gwen-web/files/950215/crash_log.txt)

Following this, I downloaded selenium v2.53.1 and set the SELENIUM_HOME variable as recommended, then re-ran the snapshot version. 

In this instance Gwen successfully navigates to flood.io, but crashed when attempting the first step:
[crash_log.txt](https://github.com/gwen-interpreter/gwen-web/files/950229/crash_log.txt)

1.8.0 is still running well using the latest java/geckodriver/firefox versions. No stress on this issue though, we're running all child-window tests in our first feature of each batch as a workaround, but happy to help you test the newer versions.

**Comment by bjuric** [comment]
Yeah, there are binary incompatibilities between selenium 2.x and 3.x and Firefox 45.x won't work with the latest selenium.

But I've applied the same change to the latest Gwen 1.x release (which is compatible with what you have) and built the following snapshot for you. Please give that a go and let me know how it goes.

[gwen-web-1.11.0-1-g2b227b5-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/1.11.0-1-g2b227b5-SNAPSHOT/gwen-web-1.11.0-1-g2b227b5-SNAPSHOT.zip)

**Comment by inkbleed** [comment]
Thanks a ton, that resolved the issue! Awesome work resolving it so quickly.

**Comment by bjuric** [comment]
Great!  Thanks for verifying that.

I've rolled this out to the [v1.11.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v1.11.1) pre-release. I'd recommend that your team update to this version for now and switch to 2.x when you're ready.

I've also included the same fix in the latest [v2.4.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.4.1) release.

**Comment by bjuric** [comment]
Close when ready, thank you.
