### ISSUE TITLE
Support for webdriver desired_capability in gwen.properties

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#43]
There should be some mechanism/configuration to support & configure webdriver desired_capabilities.

Below links contains information on the same.
https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

**Comment by bjuric** [comment]
Unfortunately the configuration of capabilities is programmatic in the selenium API and browser specific. It would therefore be difficult for us to support them all in one go. Perhaps for now if you could let us know which specific browser capability you require, we could implement it for you.

**Comment by bjuric** [comment]
@Rahul9844, I've built a snapshot below containing support for ignoring zoom settings in IE (I believe this is what you were after).  Please test it out using the following gwen setting:

`gwen.web.ignore.zoom=true`

Snapshot build: [gwen-web-2.14.3-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.14.3-SNAPSHOT/gwen-web-2.14.3-SNAPSHOT.zip)

**Comment by Rahul9844** [comment]
Thanks. GWEN is now able to startup app in I.E browser
Earlier i use to get below error on startup
Browser zoom level was set to 114%.

Now with gwen.web.ignore.zoom=true set i am no longer getting above error.

**Comment by Rahul9844** [comment]
Can you please document how the rest of the desired_capabilities are to be configured?
As I needed to set few more settings for I.E browser. (example : ignoreProtectedModeSettings)

**Comment by bjuric** [comment]
Great to hear that the zoom ignore setting works. Regarding other settings, we need to add support for them one at a time (for reasons stated above). If you could specify which ones you need exactly please.

**Comment by bjuric** [comment]
See also the complete list of already supported settings (in case the one you need is already support) here https://github.com/gwen-interpreter/gwen-web/wiki/Runtime-Settings#gwen-web-settings

**Comment by bjuric** [comment]
I'm going to take a look at this again to see if I can come up with a good settings strategy. Stay tuned.

**Comment by bjuric** [comment]
Hi, we've added a new `gwen.web.capabilities` setting in the snapshot below to support all the capabilities. You can use it to set one or more (comma separated) `name=value` capabilities for any browser.
 
For example: 
- Single setting:
  - `gwen.web.capabilities=ignoreZoomSetting=true`
- Multiple settings:
- `gwen.web.capabilities=ignoreZoomSetting=true,ignoreProtectedModeSettings=true`

Boolean, integer, and string values are supported. This setting can be used to set any browser capability. Capabilities that are not supported by a particular browser will have no effect and will be ignored.

Please try it out using the snapshot below and let us know how it goes.

- [gwen-web-2.14.3-4-g821d258-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.14.3-4-g821d258-SNAPSHOT/gwen-web-2.14.3-4-g821d258-SNAPSHOT.zip)

**Comment by Rahul9844** [comment]
It is working intermittently. But otherwise fails with 'Unable to get browser error' on startup. I have attached log file containing details about the error.

**Comment by Rahul9844** [comment]
Started InternetExplorerDriver server (32-bit)
3.4.0.0
Listening on port 37818
Only local connections are allowed
Jan 09, 2018 11:11:53 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
ERROR - Failed step [at line 65]: Given I navigate to the login page: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.23', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: http://localhost:37818/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 08388c9c-9d8f-4ecf-904a-22c5f28f9a21
INFO - Closing environment context
INFO - Closing browser session
Jan 09, 2018 11:11:56 AM org.openqa.selenium.os.OsProcess destroy
SEVERE: Unable to kill process java.lang.ProcessImpl@33aeca0b
org.openqa.selenium.NoSuchWindowException: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.23', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: http://localhost:37818/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 08388c9c-9d8f-4ecf-904a-22c5f28f9a21
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.ie.InternetExplorerDriver.getScreenshotAs(InternetExplorerDriver.java:235)
	at gwen.web.WebContext.$anonfun$captureScreenshot$2(WebContext.scala:171)
	at gwen.web.DriverManager.withWebDriver(DriverManager.scala:88)
	at gwen.web.WebContext.$anonfun$captureScreenshot$1(WebContext.scala:170)
	at gwen.eval.Evaluatable.perform(Evaluatable.scala:39)
	at gwen.eval.Evaluatable.perform$(Evaluatable.scala:39)
	at gwen.eval.EnvContext.perform(EnvContext.scala:45)
	at gwen.web.WebContext.captureScreenshot(WebContext.scala:168)
	at gwen.web.WebEnvContext.addErrorAttachments(WebEnvContext.scala:65)
	at gwen.eval.EnvContext.finaliseStep(EnvContext.scala:208)
	at gwen.eval.EvalEngine.evaluateStep(EvalEngine.scala:172)
	at gwen.eval.EvalEngine.evaluateStep$(EvalEngine.scala:131)
	at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateSteps$1(EvalEngine.scala:251)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at gwen.eval.EvalEngine.evaluateSteps(EvalEngine.scala:245)
	at gwen.eval.EvalEngine.evaluateSteps$(EvalEngine.scala:244)
	at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.evalStepDef(EvalEngine.scala:215)
	at gwen.eval.EvalEngine.evaluateStep(EvalEngine.scala:165)
	at gwen.eval.EvalEngine.evaluateStep$(EvalEngine.scala:131)
	at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateSteps$1(EvalEngine.scala:251)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at gwen.eval.EvalEngine.evaluateSteps(EvalEngine.scala:245)
	at gwen.eval.EvalEngine.evaluateSteps$(EvalEngine.scala:244)
	at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.evaluateScenario(EvalEngine.scala:92)
	at gwen.eval.EvalEngine.evaluateScenario$(EvalEngine.scala:62)
	at gwen.web.WebInterpreter.evaluateScenario(WebIntepreter.scala:27)
	at gwen.eval.GwenInterpreter.$anonfun$evaluateFeature$6(GwenInterpreter.scala:181)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at gwen.eval.GwenInterpreter.evaluateFeature(GwenInterpreter.scala:152)
	at gwen.eval.GwenInterpreter.$anonfun$interpretFeature$2(GwenInterpreter.scala:122)
	at scala.Option.map(Option.scala:146)
	at gwen.eval.GwenInterpreter.interpretFeature(GwenInterpreter.scala:103)
	at gwen.eval.GwenLauncher.evaluateUnit(GwenLauncher.scala:153)
	at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnits$11(GwenLauncher.scala:122)
	at scala.collection.immutable.Stream.foldLeft(Stream.scala:546)
	at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:118)
	at gwen.eval.GwenLauncher.run(GwenLauncher.scala:57)
	at gwen.eval.GwenApp.run(GwenApp.scala:52)
	at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
	at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at gwen.eval.GwenApp.main(GwenApp.scala:26)
	at gwen.web.WebInterpreter.main(WebIntepreter.scala)
Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.23', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: http://localhost:37818/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 08388c9c-9d8f-4ecf-904a-22c5f28f9a21

**Comment by bjuric** [comment]
Is there an alert in the browser that is interfering?

Error from log states:
unexpectedAlertBehavior: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 08388c9c-9d8f-4ecf-904a-22c5f28f9a21

**Comment by bjuric** [comment]
Actually, error is:
Unable to get browser (WARNING: The server did not provide any stacktrace information)

Are you using the latest IE driver version 3.8.0?

**Comment by bjuric** [comment]
@Rahul9844, We've added the following alternative way of setting capabilities (in addition to the CSV approach we implemented earlier).  
 
For example: 
- Single setting:
  - `gwen.web.capability.ignoreZoomSetting=true`
- Multiple settings:
   ```
   gwen.web.capability.ignoreZoomSetting=true
   gwen.web.capability.ignoreProtectedModeSettings=true
   ```

Please try it out using the snapshot below and let us know how it goes.

- [gwen-web-2.14.3-5-ga8a16ef-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.14.3-5-ga8a16ef-SNAPSHOT/gwen-web-2.14.3-5-ga8a16ef-SNAPSHOT.zip)

Also, can you try upgrading to a later IE driver (latest is version 3.8.0) to see if it resolves the intermittent issue in your previous comment?

**Comment by Rahul9844** [comment]
@bjuric I used gwen-web-2.14.3-5-ga8a16ef-SNAPSHOT.zip and IE Driver : 3.8.0
It worked on first attempt. But typing on textbox was very slow (sleep of 1 sec after each char input)
I reran again for confirming the current issue is resolved and it started giving the same error again.
**Unable to get browser**.

**Comment by bjuric** [comment]
I have observed the typing slow behavior with 64 bit driver and found that switching to the 32 bit version fixed the issue. Try switching if you are using the 64 bit driver.

**Comment by bjuric** [comment]
Have a look at this link and see if that helps
- http://www.michael-whelan.net/selenium-webdriver-and-ie11/

And another which suggests that Microsoft is aware of the issue but haven't fixed it. A lot of users in this link having the same issue. 
-  https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6511

I'm not sure if you've configured the `ignoreProtectedModeSettings` capability to true. If so, please remove that setting.

For a lot of people, getting IE working involves a lot of trial and error of different driver/browser versions and/or settings. It's unfortunate. 

If you remove all your recent capabilities settings that you are testing as part of this GitHub issue, do your tests work as before? If not, what has changed?

**Comment by bjuric** [comment]
Looking at your trace provided earlier above, I can see `ignoreProtectedModeSettings: true`.
Please remove that setting and try again. I'm suspecting that setting it to true is causing instability (I've made it false in my examples above).

**Comment by bjuric** [comment]
@Rahul9844, can you retest with `gwen.web.capability.ignoreProtectedModeSettings=false` please?

**Comment by Rahul9844** [comment]
Tested with gwen.web.capability.ignoreProtectedModeSettings=false

**Comment by bjuric** [comment]
Do you still have this one set (the previous CSV alternative)?
- `gwen.web.capabilities=ignoreZoomSetting=true,ignoreProtectedModeSettings=true`

**Comment by Rahul9844** [comment]
I tried without the property and the issue is still reproducible. 
FYI : I am testing on **gwen-web-2.14.3-5-SNAPSHOT**

**Comment by Rahul9844** [comment]
ERROR - Failed step [at line 6]: And I navigate to "http://www.google.com/": Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.27', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:44092/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: c088fc53-1015-48a9-a2cb-efa0da23c5d8
INFO - Closing environment context
INFO - Closing browser session
org.openqa.selenium.NoSuchWindowException: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.27', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:44092/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: c088fc53-1015-48a9-a2cb-efa0da23c5d8
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
        at org.openqa.selenium.ie.InternetExplorerDriver.getScreenshotAs(InternetExplorerDriver.java:235)
        at gwen.web.WebContext.$anonfun$captureScreenshot$2(WebContext.scala:171)
        at gwen.web.DriverManager.withWebDriver(DriverManager.scala:88)
        at gwen.web.WebContext.$anonfun$captureScreenshot$1(WebContext.scala:170)
        at gwen.eval.Evaluatable.perform(Evaluatable.scala:39)
        at gwen.eval.Evaluatable.perform$(Evaluatable.scala:39)
        at gwen.eval.EnvContext.perform(EnvContext.scala:45)
        at gwen.web.WebContext.captureScreenshot(WebContext.scala:168)
        at gwen.web.WebEnvContext.addErrorAttachments(WebEnvContext.scala:65)
        at gwen.eval.EnvContext.finaliseStep(EnvContext.scala:208)
        at gwen.eval.EvalEngine.evaluateStep(EvalEngine.scala:174)
        at gwen.eval.EvalEngine.evaluateStep$(EvalEngine.scala:131)
        at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
        at gwen.eval.EvalEngine.$anonfun$evaluateSteps$1(EvalEngine.scala:253)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at gwen.eval.EvalEngine.evaluateSteps(EvalEngine.scala:247)
        at gwen.eval.EvalEngine.evaluateSteps$(EvalEngine.scala:246)
        at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
        at gwen.eval.EvalEngine.evaluateScenario(EvalEngine.scala:92)
        at gwen.eval.EvalEngine.evaluateScenario$(EvalEngine.scala:62)
        at gwen.web.WebInterpreter.evaluateScenario(WebIntepreter.scala:27)
        at gwen.eval.GwenInterpreter.$anonfun$evaluateFeature$6(GwenInterpreter.scala:181)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at gwen.eval.GwenInterpreter.evaluateFeature(GwenInterpreter.scala:152)
        at gwen.eval.GwenInterpreter.$anonfun$interpretFeature$2(GwenInterpreter.scala:122)
        at scala.Option.map(Option.scala:146)
        at gwen.eval.GwenInterpreter.interpretFeature(GwenInterpreter.scala:103)
        at gwen.eval.GwenLauncher.evaluateUnit(GwenLauncher.scala:153)
        at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnits$11(GwenLauncher.scala:122)
        at scala.collection.immutable.Stream.foldLeft(Stream.scala:546)
        at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:118)
        at gwen.eval.GwenLauncher.run(GwenLauncher.scala:57)
        at gwen.eval.GwenApp.run(GwenApp.scala:52)
        at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
        at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at gwen.eval.GwenApp.main(GwenApp.scala:26)
        at gwen.web.WebInterpreter.main(WebIntepreter.scala)
Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MUM-MOB0144', ip: '192.168.162.27', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:44092/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: c088fc53-1015-48a9-a2cb-efa0da23c5d8

**Comment by bjuric** [comment]
Please test this without the capabilities settings using the previous stable release [gwen-web-2.14.3.zip](https://github.com/gwen-interpreter/gwen-web/releases/download/v2.14.3/gwen-web-2.14.3.zip).

I would like to rule out environmental issues.

**Comment by bjuric** [comment]
@Rahul9844, I tested this using the on a Windows 10 environment with IE 11 and did not get the errors you are seeing. I tried it using the gwen-web-2.14.3-5-SNAPSHOT and also the latest 2.15.0 gwen-web release (where i added capability settings support). The capability settings worked as expected. I also tested the initialBrowserUrl IE setting in addition to the above and it worked OK.

I cannot replicate the error you are getting.

But it looks like you're using Windows 7 according to your trace. Is that correct? If so, you may need to backtrack to a much older native IE driver. If you revert to what you had before raising this issue, do you still get this "unable to get browser" error?

**Comment by bjuric** [comment]
@Rahul9844, we've added support for capabilities. If you believe your issue is environmental or native driver related, please close this one.

Perhaps check that all security zones in IE are set to the same Protected Mode setting. Setting the Local Intranet zone's Enable Protected Mode setting to true can also solve this problem.

Seems many others are having similar issues with IE here: https://stackoverflow.com/questions/45073995/ie11-exceptions-with-iedriverserver-unable-to-get-browser
