### ISSUE TITLE
Gwen fails with error if it encounters any keywords in validation of Text.

### ISSUE THREAD

**Issue by ketu4u2010** [gwen-interpreter/gwen-web#45]
Gwen fails with error if it encounters any keywords in validation of Text.

STMT:
And 57A: Account with Institution MT103 Remit description is "This field specifies the financial institution which services the account for the beneficiary customer. This is applicable even if field 59a contains an IBAN."

Error:
INFO - Closing environment context
INFO - Closing browser session
gwen.errors.package$EvaluationException: Failed to load meta: Config Meta: Failed step [at line 343]: And 57A: Account with Institution MT103 Remit description is "This field specifies the financial institution which services the account for the beneficiary customer. This is applicable even if field 59a contains an IBAN.": Unbound reference in login page scope: field 59a contains an IBAN."/javascript
       at gwen.errors.package$.evaluationError(errors.scala:44)
       at gwen.eval.GwenInterpreter.$anonfun$loadMetaFile$1(GwenInterpreter.scala:255)
       at gwen.Predefs$Kestrel$.tap$extension(Predefs.scala:46)
       at gwen.eval.GwenInterpreter.loadMetaFile(GwenInterpreter.scala:248)
       at gwen.eval.GwenInterpreter.$anonfun$loadMetaImports$1(GwenInterpreter.scala:212)
       at scala.collection.immutable.List.flatMap(List.scala:335)
       at gwen.eval.GwenInterpreter.loadMetaImports(GwenInterpreter.scala:210)
       at gwen.eval.GwenInterpreter.$anonfun$interpretFeature$2(GwenInterpreter.scala:116)
       at scala.Option.map(Option.scala:146)
       at gwen.eval.GwenInterpreter.interpretFeature(GwenInterpreter.scala:103)
       at gwen.eval.GwenLauncher.evaluateUnit(GwenLauncher.scala:153)
       at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnits$11(GwenLauncher.scala:122)
       at scala.collection.immutable.Stream.foldLeft(Stream.scala:546)
       at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:118)
       at gwen.eval.GwenLauncher.run(GwenLauncher.scala:57)
       at gwen.eval.GwenApp.run(GwenApp.scala:52)
       at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
       at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
       at scala.Function0.apply$mcV$sp(Function0.scala:34)
       at scala.Function0.apply$mcV$sp$(Function0.scala:34)
       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
       at scala.App.$anonfun$main$1$adapted(App.scala:76)
       at scala.collection.immutable.List.foreach(List.scala:389)
       at scala.App.main(App.scala:76)
       at scala.App.main$(App.scala:74)
       at gwen.eval.GwenApp.main(GwenApp.scala:26)
       at gwen.web.WebInterpreter.main(WebIntepreter.scala)
Failed to load meta: Config Meta: Failed step [at line 343]: And 57A: Account with Institution MT103 Remit description is "This field specifies the financial institution which services the account for the beneficiary customer. This is applicable even if field 59a contains an IBAN.": Unbound reference in login page scope: field 59a contains an IBAN."/javascript

If i change the description to say "ABCD" same stmt works fine

**Comment by bjuric** [comment]
@ketu4u2010 Thanks for raising this. We put in a fix for this in the snapshot build below. Please try it out and let us know how it goes.

- [gwen-web-2.14.3-5-gf3a1734-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.14.3-5-gf3a1734-SNAPSHOT/gwen-web-2.14.3-5-gf3a1734-SNAPSHOT.zip)

**Comment by ketu4u2010** [comment]
@bjuric  Changes worked as expected. By when will you merge this to main build? Atm i will use snapshot to proceed further.

**Comment by bjuric** [comment]
Thanks. We will release this once issue #43 is also closed.
