### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Implementing class

### ISSUE THREAD

**Issue by Jpshukla185** [gwen-interpreter/gwen-web#64]
I M just starting to learn and use gwen but I am not getting console with gwen prompt.
{code}
E:\GWEN\gwen-workspace>gwen.bat
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install gwen-web gwen.gwen-web.version target\gwen-packages\gwen-web
[gwen-gpm] Target gwen-web version is 2.26.0
[gwen-gpm] gwen-web-2.26.0 exists in download cache
[gwen-gpm] gwen-web-2.26.0 already installed in target/gwen-packages/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install chrome-driver gwen.chrome-driver.version target\gwen-packages\chrome-driver
[gwen-gpm] Target chrome-driver version is 2.42
[gwen-gpm] chrome-driver-2.42 exists in download cache
[gwen-gpm] chrome-driver-2.42 already installed in target/gwen-packages/chrome-driver
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install selenium gwen.selenium.version target\gwen-packages\selenium
[gwen-gpm] selenium is provided by Gwen
ECHO is off.
Launching Gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.26.0

INFO - GWEN_CLASSPATH = E:\JDBC\forgwen\ojdbc6.jar;E:\JDBC\forgwen\sqljdbc4-2.0.jar
INFO - Environment context initialised
INFO - gwen-web.bat -m meta -r target/reports -p gwen.properties

REPL Console

Enter steps to evaluate or type exit to quit..

INFO - Closing environment context
java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at gwen.eval.GwenREPL.reader$lzycompute(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.reader(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.read(GwenREPL.scala:58)
        at gwen.eval.GwenREPL.run(GwenREPL.scala:165)
        at gwen.eval.GwenApp.$anonfun$run$2(GwenApp.scala:60)
        at gwen.eval.GwenApp.$anonfun$run$2$adapted(GwenApp.scala:56)
        at scala.Option.foreach(Option.scala:257)
        at gwen.eval.GwenApp.$anonfun$run$1(GwenApp.scala:56)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
        at gwen.Predefs$Kestrel$.tap$extension(Predefs.scala:49)
        at gwen.eval.GwenApp.run(GwenApp.scala:55)
        at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
        at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at gwen.eval.GwenApp.main(GwenApp.scala:26)
        at gwen.web.WebInterpreter.main(WebIntepreter.scala)
ERROR - Implementing class
{code}

**Comment by Jpshukla185** [comment]
I am using Window-7

**Comment by bjuric** [comment]
Can you try clearing GWEN_CLASSPATH environment variable and launch again? Just want to rule out binary incomparability of those SQL jars.

Also, are you running as admin in windows terminal?

**Comment by Jpshukla185** [comment]
Removed GWEN_CLASSPATH, Run command line using  Administrator option...
But results are the same.

**Comment by Jpshukla185** [comment]
E:\GWEN\gwen-workspace>gwen.bat
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install gwen-web gwen.gwen-web.version target\gwen
-packages\gwen-web
[gwen-gpm] Target gwen-web version is 2.26.0
[gwen-gpm] gwen-web-2.26.0 exists in download cache
[gwen-gpm] gwen-web-2.26.0 already installed in target/gwen-packages/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install chrome-driver gwen.chrome-driver.version t
arget\gwen-packages\chrome-driver
[gwen-gpm] Target chrome-driver version is 2.42
[gwen-gpm] chrome-driver-2.42 exists in download cache
[gwen-gpm] chrome-driver-2.42 already installed in target/gwen-packages/chrome-d
river
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install selenium gwen.selenium.version target\gwen
-packages\selenium
[gwen-gpm] selenium is provided by Gwen
ECHO is off.
Launching Gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.26.0

INFO - Environment context initialised
INFO - gwen-web.bat -m meta -r target/reports -p gwen.properties

REPL Console

Enter steps to evaluate or type exit to quit..

INFO - Closing environment context
java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at gwen.eval.GwenREPL.reader$lzycompute(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.reader(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.read(GwenREPL.scala:58)
        at gwen.eval.GwenREPL.run(GwenREPL.scala:165)
        at gwen.eval.GwenApp.$anonfun$run$2(GwenApp.scala:60)
        at gwen.eval.GwenApp.$anonfun$run$2$adapted(GwenApp.scala:56)
        at scala.Option.foreach(Option.scala:257)
        at gwen.eval.GwenApp.$anonfun$run$1(GwenApp.scala:56)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:
12)
        at gwen.Predefs$Kestrel$.tap$extension(Predefs.scala:49)
        at gwen.eval.GwenApp.run(GwenApp.scala:55)
        at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:3
2)
        at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:
12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at gwen.eval.GwenApp.main(GwenApp.scala:26)
        at gwen.web.WebInterpreter.main(WebIntepreter.scala)
ERROR - Implementing class

E:\GWEN\gwen-workspace>

**Comment by Jpshukla185** [comment]
this is my Class Path details:
"C:\Program Files\Java\jdk1.8.0_131\bin;E:\Program Files (x86)\qfs\qftest\plugin\ojdbc6;E:;C:\Program Files\Java\jdk1.8.0_131\bin"

This is path Details:
"C:\Program Files\Java\jdk1.8.0_131\bin;C:\ProgramData\Oracle\Java\javapath;E:\app\jshukla\product\11.2.0\client_1;E:\app\Jshukla\product\11.2.1\dbhome_2;E:\app\Jshukla\product\11.2.0\dbhome_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;E:\Program Files (x86)\Tools;E:\app\Jshukla\product\11.2.0\instantclient_11_2;E:\smartrecs\codecoverage\apache-maven-3.2.1\bin;E:\smartrecs\codecoverage\apache-maven-3.2.1\bin;%GWEN_CLASSPATH%;C:\Program Files\Java\jdk1.8.0_131\bin"

**Comment by bjuric** [comment]
Can you check if you have any jline jar files in your java home at `Library/Java/Extensions` or `/System/Library/Java/Extensions`?

**Comment by bjuric** [comment]
If not, please try gwen-web version 2.24.0. If you're using a Gwen workspace, just change this property in your `gwen.properties` file and launch again:

`gwen.gwen-web.version=2.24.0`

**Comment by Jpshukla185** [comment]
Nope , I could not find any jline jar files in My JAVA_HOME path.
![image](https://user-images.githubusercontent.com/43437422/45813871-6dcb9980-bcf1-11e8-8310-e76d0f018787.png)

**Comment by bjuric** [comment]
Did you try gwen-web version 2.24.0 (as per above)?

**Comment by Jpshukla185** [comment]
yes trying as per your instructions but hard luck installation fails, could not backup the previous one..

E:\GWEN\gwen-workspace>gwen.bat
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install gwen-web gwen.gwen-web.version target\gwen
-packages\gwen-web
[gwen-gpm] Target gwen-web version is 2.24.0
[gwen-gpm] Downloading gwen-web-2.24.0 from https://github.com/gwen-interpreter/
gwen-web/releases/download/v2.24.0/gwen-web-2.24.0.zip
[gwen-gpm] [============================] 100% 19s
[gwen-gpm] Checksum OK
[gwen-gpm] Download done
[gwen-gpm] Found gwen-web-2.26.0 installation at: target/gwen-packages/gwen-web
[gwen-gpm] Backing up existing installation to: C:/Users/Jshukla/.gwen/backup/gw
en-web/gwen-web-2.26.0-bak-20180920-164047.zip
[gwen-gpm] Failed with error: Could not create backup of existing installation:
target\gwen-packages\gwen-web
Failed to auto-install gwen-web

**Comment by bjuric** [comment]
Delete the `workspace\target` folder and try again. Thanks

**Comment by Jpshukla185** [comment]
yes that way it worked now... new installation is done .. but the same error
E:\GWEN\gwen-workspace>gwen.bat
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install gwen-web gwen.gwen-web.version target\gwen-packages\gwen-web
[gwen-gpm] Target gwen-web version is 2.24.0
[gwen-gpm] gwen-web-2.24.0 exists in download cache
[gwen-gpm] Found gwen-web-2.26.0 installation at: target/gwen-packages/gwen-web
[gwen-gpm] Backing up existing installation to: C:/Users/Jshukla/.gwen/backup/gwen-web/gwen-web-2.26.0-bak-20180920-165806.zip
[gwen-gpm] Failed with error: Could not create backup of existing installation: target\gwen-packages\gwen-web
Failed to auto-install gwen-web

E:\GWEN\gwen-workspace>gwen.bat
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install gwen-web gwen.gwen-web.version target\gwen-packages\gwen-web
[gwen-gpm] Target gwen-web version is 2.24.0
[gwen-gpm] gwen-web-2.24.0 exists in download cache
[gwen-gpm] Installing gwen-web-2.24.0 to target/gwen-packages/gwen-web
[gwen-gpm] Checksum OK
[gwen-gpm] Install done
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install chrome-driver gwen.chrome-driver.version target\gwen-packages\chrome-driver
[gwen-gpm] Target chrome-driver version is 2.42
[gwen-gpm] Downloading chrome-driver-2.42 from https://chromedriver.storage.googleapis.com/2.42/chromedriver_win32.zip
[gwen-gpm] [============================] 100% 5s
[gwen-gpm] Checksum OK
[gwen-gpm] Download done
[gwen-gpm] Installing chrome-driver-2.42 to target/gwen-packages/chrome-driver
[gwen-gpm] Checksum OK
[gwen-gpm] Install done
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v1.1.1
   `
[gwen-gpm] -p gwen.properties install selenium gwen.selenium.version target\gwen-packages\selenium
[gwen-gpm] selenium is provided by Gwen
ECHO is off.
Launching Gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.24.0

INFO - Environment context initialised
INFO - gwen-web.bat -m meta -r target/reports -p gwen.properties

REPL Console

Enter steps to evaluate or type exit to quit..

INFO - Closing environment context
java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at gwen.eval.GwenREPL.reader$lzycompute(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.reader(GwenREPL.scala:46)
        at gwen.eval.GwenREPL.read(GwenREPL.scala:58)
        at gwen.eval.GwenREPL.run(GwenREPL.scala:165)
        at gwen.eval.GwenApp.$anonfun$run$2(GwenApp.scala:60)
        at gwen.eval.GwenApp.$anonfun$run$2$adapted(GwenApp.scala:56)
        at scala.Option.foreach(Option.scala:257)
        at gwen.eval.GwenApp.$anonfun$run$1(GwenApp.scala:56)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
        at gwen.Predefs$Kestrel$.tap$extension(Predefs.scala:49)
        at gwen.eval.GwenApp.run(GwenApp.scala:55)
        at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
        at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at gwen.eval.GwenApp.main(GwenApp.scala:26)
        at gwen.web.WebInterpreter.main(WebIntepreter.scala)
ERROR - Implementing class

**Comment by bjuric** [comment]
Try gwen-web version `2.14.0` please? It's quite an older version. But want to rule out recent library updates. thanks

**Comment by Jpshukla185** [comment]
Nope result is same with 2.14.0, I think it has something to do with java libraries on my local machine...but some how i am not able to identify the root cause. , I have also tried with JDK versions jdk1.8.0_131,jdk1.8.0_144 as well but result are same.

**Comment by bjuric** [comment]
OK, this confirms it's not related to recent library updates in Gwen. Rather it's something environmental. Does this only happen in your current environment? Have you tried other windows machines?

**Comment by Jpshukla185** [comment]
It works on other's machine. But not on mine.

**Comment by bjuric** [comment]
Usually people say "works on my machine". This is a tough one.

**Comment by bjuric** [comment]
Try java 9

**Comment by Jpshukla185** [comment]
What difference it will make?

**Comment by Jpshukla185** [comment]
Yes it could be as on company laptop with specific security policy. But My user has admin rights and I do run many other application like weblogic etc on my local...something wrong with classloader but difficult to make it out. let us leave this for now..

**Comment by bradywood** [comment]
We could also try with a clean environment.  eg.  ensure path only contains one java path.  (as you open an admin terminal/command prompt) will unset all the environment variables for this session.

Then just make sure only the following are set.
JAVA_HOME=..
PATH=c:\..JAVA only..

Also could you try installing in a directory that perhaps doesn’t have spaces, eg  c:\TMP or c:\DEV or something.
I am purely trying to rule out items.

**Comment by bjuric** [comment]
Revert back to latest gwen and try adding the following setting to your `workspace/gwen.properties` file:
- `jline.terminal=win`

Then launch gwen. If you still have issues, try..

- `jline.terminal=windows`
