### ISSUE TITLE
problem loading .meta files

### ISSUE THREAD

**Issue by bitcoder** [gwen-interpreter/gwen-web#68]
I'm unsure if this is a bug or not but from the description on the [wiki](https://github.com/gwen-interpreter/gwen/wiki/Meta-Features) it seems that .meta files are loaded:

- all .meta files from the directory identified with the "-m" parameter
- all .meta files from the current directory and all subdirectories

From my understanding, .meta files can be in a totally different place where the respective feature lives, and also the name can be whatever.
Are these assumptions correct?

I've download the gwen-workspace from https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.34.1.
If I run those features, as is, using ./gwen from my Mac environment, it works fine.
However, I've done the following:
- in that workspace, I've moved out the .meta files from the features subdirectory to the "meta" subdirectory.

Calling gwen does not work in this case:

`
$ ./gwen -b features
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update gwen-web gwen.gwen-web.version target/gwen/gwen-web -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] Target gwen-web version is latest
[gwen-gpm] The latest available gwen-web version is 2.34.1
[gwen-gpm] You'll be using the latest gwen-web ..Very good!
[gwen-gpm] gwen-web-2.34.1 exists in download cache
[gwen-gpm] gwen-web-2.34.1 already installed in target/gwen/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update selenium gwen.selenium.version target/gwen/selenium -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] selenium is provided by Gwen

Launching gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.34.1

INFO - gwen-web.sh -m meta -r target/reports -p gwen.properties,browsers/chrome.properties,env/local.properties -b features
INFO - Found FeatureUnit(features/2_CALC-4805.feature,List(meta/google/Google.meta, meta/floodio/FloodIO.meta),None)
INFO - Found FeatureUnit(features/1_CALC-4806.feature,List(meta/google/Google.meta, meta/floodio/FloodIO.meta),None)
INFO -
  _
 { \," Evaluating feature..
{_`/   features/2_CALC-4805.feature
   `
INFO - Environment context initialised
INFO -
INFO - Loading meta: Google search meta [file: meta/google/Google.meta]
INFO - Loading StepDef: I have Google in my browser
INFO - Loading StepDef: I do a search for "<query>"
INFO - Loading StepDef: the first result should open a Gwen page
INFO - Loaded meta: Google search meta [file: meta/google/Google.meta]
INFO - [~0ms] Loaded [:)], [31ms] Overhead, [31ms] Elapsed, Started: Mon Jul 29 17:17:21 WEST 2019, Finished: Mon Jul 29 17:17:21 WEST 2019
INFO -
INFO - Loading meta: floodio meta [file: meta/floodio/FloodIO.meta]
INFO - Evaluating Scenario: Initialise
INFO - Evaluating Step: Given the heading is displayed is defined by javascript "!!$('h2')"
INFO - [22ms] Passed Step: Given the heading is displayed is defined by javascript "!!$('h2')"
INFO - Evaluating Step: And the heading can be located by tag name "h2"
INFO - [4ms] Passed Step: And the heading can be located by tag name "h2"
INFO - Evaluating Step: And the next button can be located by class name "btn"
INFO - [2ms] Passed Step: And the next button can be located by class name "btn"
INFO - [28ms] Passed Scenario: Initialise
INFO - Loading StepDef: I launch the floodio challenge
INFO - Loading StepDef: I am on the <page-name> page
INFO - Loading StepDef: I should be on the start page
INFO - Loading StepDef: I should be on the step 2 page
INFO - Loading StepDef: I should be on the step 3 page
INFO - Loading StepDef: I should be on the step 4 page
INFO - Loading StepDef: I should be on the step 5 page
INFO - Loading StepDef: I should be on the challenge completed page
INFO - Loading StepDef: I select and enter the largest order value
INFO - Loading StepDef: I enter the one time token
INFO - Loaded meta: floodio meta [file: meta/floodio/FloodIO.meta]
INFO - [28ms] Passed [:)], [28ms] Overhead, [56ms] Elapsed, Started: Mon Jul 29 17:17:21 WEST 2019, Finished: Mon Jul 29 17:17:21 WEST 2019
INFO -
INFO - Evaluating feature: Google search (gwen-web-demo) [file: features/2_CALC-4805.feature]
INFO - Evaluating Scenario: Perform a google search
INFO - Evaluating Step: Given I have Google in my browser
INFO - Evaluating Step: Given I start a new browser
INFO - Switching to browser session: primary
INFO - Starting chrome browser session
INFO - Using chromedriver 75.0.3770.140 (since Google Chrome 75 is installed in your machine)
INFO - Exporting webdriver.chrome.driver as /Users/smsf/.gwen/wdm/chromedriver/mac64/75.0.3770.140/chromedriver
INFO - Setting chrome argument: --ignore-certificate-errors
INFO - Setting web capability: acceptSslCerts=true
INFO - Setting web capability: javascriptEnabled=true
Starting ChromeDriver 75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}) on port 44672
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jul 29, 2019 5:17:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
INFO - Implicit wait (default locator timeout) = 5 second(s)
INFO - [1s 755ms] Passed Step: Given I start a new browser
INFO - Evaluating Step: When I navigate to "http://www.google.com"
INFO - [673ms] Passed Step: When I navigate to "http://www.google.com"
INFO - Evaluating Step: Then the page title should be "Google"
INFO - [28ms] Passed Step: Then the page title should be "Google"
INFO - [2s 457ms] Passed Step: Given I have Google in my browser
INFO - Evaluating Step: When I do a search for "Gwen automation"
INFO - Evaluating Step: Given the search field can be located by name "q"
INFO - [2ms] Passed Step: Given the search field can be located by name "q"
INFO - Evaluating Step: When I enter "Gwen automation" in the search field
INFO - [2s 046ms] Passed Step: When I enter "Gwen automation" in the search field
INFO - Evaluating Step: Then the page title should contain "Gwen automation"
INFO - [9ms] Passed Step: Then the page title should contain "Gwen automation"
INFO - [2s 058ms] Passed Step: When I do a search for "Gwen automation"
INFO - Evaluating Step: Then the first result should open a Gwen page
INFO - Evaluating Step: Given the first match can be located by css selector ".r > a"
INFO - [2ms] Passed Step: Given the first match can be located by css selector ".r > a"
INFO - Evaluating Step: When I click the first match
INFO - [3s 154ms] Passed Step: When I click the first match
INFO - Evaluating Step: Then the current URL should contain "gwen-interpreter"
ERROR - {
  scopes {
    scope : "feature" {
      the heading is displayed/javascript : "!!$('h2')"
      the heading/locator : "tag name"
      the heading/locator/tag name : "h2"
      the next button/locator : "class name"
      the next button/locator/class name : "btn"
      gwen.feature.file.name : "2_CALC-4805.feature"
      gwen.feature.file.path : "features/2_CALC-4805.feature"
      gwen.feature.file.absolutePath : "/Users/smsf/exps/gwen-workspace/features/2_CALC-4805.feature"
      gwen.feature.name : "Google search (gwen-web-demo)"
      gwen.scenario.name : "Perform a google search"
      page/title : "Google"
      the search field/locator : "name"
      the search field/locator/name : "q"
      the search field/type : "Gwen automation"
      the search field/enter : "true"
      page/title : "Gwen automation - Google Search"
      the first match/locator : "css selector"
      the first match/locator/css selector : ".r > a"
      the first match/click : "true"
      the current URL : "https://gweninterpreter.wordpress.com/"
    }
  }
}
ERROR - Failed step [at line 19]: Then the current URL should contain "gwen-interpreter": assertion failed: Expected the current URL to contain 'gwen-interpreter' but got 'https://gweninterpreter.wordpress.com/'
ERROR - [211ms] Failed Step: Then the current URL should contain "gwen-interpreter"
ERROR - {
  scopes {
    scope : "feature" {
      the heading is displayed/javascript : "!!$('h2')"
      the heading/locator : "tag name"
      the heading/locator/tag name : "h2"
      the next button/locator : "class name"
      the next button/locator/class name : "btn"
      gwen.feature.file.name : "2_CALC-4805.feature"
      gwen.feature.file.path : "features/2_CALC-4805.feature"
      gwen.feature.file.absolutePath : "/Users/smsf/exps/gwen-workspace/features/2_CALC-4805.feature"
      gwen.feature.name : "Google search (gwen-web-demo)"
      gwen.scenario.name : "Perform a google search"
      page/title : "Google"
      the search field/locator : "name"
      the search field/locator/name : "q"
      the search field/type : "Gwen automation"
      the search field/enter : "true"
      page/title : "Gwen automation - Google Search"
      the first match/locator : "css selector"
      the first match/locator/css selector : ".r > a"
      the first match/click : "true"
      the current URL : "https://gweninterpreter.wordpress.com/"
    }
  }
}
ERROR - Failed step [at line 19]: Then the current URL should contain "gwen-interpreter": assertion failed: Expected the current URL to contain 'gwen-interpreter' but got 'https://gweninterpreter.wordpress.com/'
ERROR - [3s 366ms] Failed Step: Then the first result should open a Gwen page
ERROR - [7s 881ms] Failed Scenario: Perform a google search
INFO - Evaluated feature: Google search (gwen-web-demo) [file: features/2_CALC-4805.feature]
ERROR - [7s 909ms] Failed feature: Google search (gwen-web-demo)
INFO - Slideshow feature detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/2_CALC-4805/2_CALC-4805.feature.slideshow.html
INFO - HTML feature detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/2_CALC-4805/2_CALC-4805.feature.html
INFO - HTML meta detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/2_CALC-4805/meta/0001-Google.meta.html
INFO - HTML meta detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/2_CALC-4805/meta/0002-FloodIO.meta.html
INFO - HTML feature summary report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/feature-summary.html
INFO -
INFO - [7s 909ms] Failed [:(], [1s 897ms] Overhead, [9s 865ms] Elapsed, Started: Mon Jul 29 17:17:21 WEST 2019, Finished: Mon Jul 29 17:17:30 WEST 2019
INFO -
INFO - Closing environment context
INFO - Closing browser session
INFO -
  _
 { \," Evaluating feature..
{_`/   features/1_CALC-4806.feature
   `
INFO - Environment context initialised
INFO -
INFO - Loading meta: Google search meta [file: meta/google/Google.meta]
INFO - Loading StepDef: I have Google in my browser
INFO - Loading StepDef: I do a search for "<query>"
INFO - Loading StepDef: the first result should open a Gwen page
INFO - Loaded meta: Google search meta [file: meta/google/Google.meta]
INFO - [~0ms] Loaded [:)], [~0ms] Overhead, [~0ms] Elapsed, Started: Mon Jul 29 17:17:31 WEST 2019, Finished: Mon Jul 29 17:17:31 WEST 2019
INFO -
INFO - Loading meta: floodio meta [file: meta/floodio/FloodIO.meta]
INFO - Evaluating Scenario: Initialise
INFO - Evaluating Step: Given the heading is displayed is defined by javascript "!!$('h2')"
INFO - [2ms] Passed Step: Given the heading is displayed is defined by javascript "!!$('h2')"
INFO - Evaluating Step: And the heading can be located by tag name "h2"
INFO - [1ms] Passed Step: And the heading can be located by tag name "h2"
INFO - Evaluating Step: And the next button can be located by class name "btn"
INFO - [1ms] Passed Step: And the next button can be located by class name "btn"
INFO - [4ms] Passed Scenario: Initialise
INFO - Loading StepDef: I launch the floodio challenge
INFO - Loading StepDef: I am on the <page-name> page
INFO - Loading StepDef: I should be on the start page
INFO - Loading StepDef: I should be on the step 2 page
INFO - Loading StepDef: I should be on the step 3 page
INFO - Loading StepDef: I should be on the step 4 page
INFO - Loading StepDef: I should be on the step 5 page
INFO - Loading StepDef: I should be on the challenge completed page
INFO - Loading StepDef: I select and enter the largest order value
INFO - Loading StepDef: I enter the one time token
INFO - Loaded meta: floodio meta [file: meta/floodio/FloodIO.meta]
INFO - [4ms] Passed [:)], [4ms] Overhead, [8ms] Elapsed, Started: Mon Jul 29 17:17:31 WEST 2019, Finished: Mon Jul 29 17:17:31 WEST 2019
INFO -
INFO - Evaluating feature: Complete the floodio challenge (gwen-web-demo) [file: features/1_CALC-4806.feature]
INFO - Evaluating Scenario: Verify robot completion
INFO - Evaluating Step: Given I am on the challenge completed page
INFO - Evaluating Step: Given I wait until the heading is displayed
INFO - Starting chrome browser session
INFO - Setting chrome argument: --ignore-certificate-errors
INFO - Setting web capability: acceptSslCerts=true
INFO - Setting web capability: javascriptEnabled=true
Starting ChromeDriver 75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}) on port 46129
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jul 29, 2019 5:17:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
INFO - Implicit wait (default locator timeout) = 5 second(s)
ERROR - {
  scopes {
    scope : "feature" {
      the heading is displayed/javascript : "!!$('h2')"
      the heading/locator : "tag name"
      the heading/locator/tag name : "h2"
      the next button/locator : "class name"
      the next button/locator/class name : "btn"
      gwen.feature.file.name : "1_CALC-4806.feature"
      gwen.feature.file.path : "features/1_CALC-4806.feature"
      gwen.feature.file.absolutePath : "/Users/smsf/exps/gwen-workspace/features/1_CALC-4806.feature"
      gwen.feature.name : "Complete the floodio challenge (gwen-web-demo)"
      gwen.scenario.name : "Verify robot completion"
    }
  }
}
ERROR - Failed step [at line 31]: Given I wait until the heading is displayed: Failed to execute JavaScript: !!$('h2')
ERROR - Exception:
gwen.errors.package$StepFailure: Failed step [at line 31]: Given I wait until the heading is displayed: Failed to execute JavaScript: !!$('h2')
	at gwen.eval.EvalEngine.doEvaluate(EvalEngine.scala:230)
	at gwen.eval.EvalEngine.doEvaluate$(EvalEngine.scala:212)
	at gwen.web.WebInterpreter.doEvaluate(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateStep$5(EvalEngine.scala:159)
	at scala.Option.getOrElse(Option.scala:138)
	at gwen.eval.EvalEngine.evaluateStep(EvalEngine.scala:149)
	at gwen.eval.EvalEngine.evaluateStep$(EvalEngine.scala:139)
	at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateSteps$1(EvalEngine.scala:288)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at gwen.eval.EvalEngine.evaluateSteps(EvalEngine.scala:276)
	at gwen.eval.EvalEngine.evaluateSteps$(EvalEngine.scala:275)
	at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.evalStepDef(EvalEngine.scala:244)
	at gwen.eval.EvalEngine.$anonfun$evaluateStep$5(EvalEngine.scala:183)
	at scala.Option.getOrElse(Option.scala:138)
	at gwen.eval.EvalEngine.evaluateStep(EvalEngine.scala:149)
	at gwen.eval.EvalEngine.evaluateStep$(EvalEngine.scala:139)
	at gwen.web.WebInterpreter.evaluateStep(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateSteps$1(EvalEngine.scala:288)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at gwen.eval.EvalEngine.evaluateSteps(EvalEngine.scala:276)
	at gwen.eval.EvalEngine.evaluateSteps$(EvalEngine.scala:275)
	at gwen.web.WebInterpreter.evaluateSteps(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.evaluateScenario(EvalEngine.scala:100)
	at gwen.eval.EvalEngine.evaluateScenario$(EvalEngine.scala:67)
	at gwen.web.WebInterpreter.evaluateScenario(WebIntepreter.scala:27)
	at gwen.eval.GwenInterpreter.$anonfun$evaluateFeature$6(GwenInterpreter.scala:184)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at gwen.eval.GwenInterpreter.evaluateFeature(GwenInterpreter.scala:153)
	at gwen.eval.GwenInterpreter.$anonfun$interpretFeature$2(GwenInterpreter.scala:120)
	at scala.Option.map(Option.scala:163)
	at gwen.eval.GwenInterpreter.interpretFeature(GwenInterpreter.scala:101)
	at gwen.eval.GwenLauncher.evaluateUnit(GwenLauncher.scala:176)
	at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnitsSequential$1(GwenLauncher.scala:143)
	at scala.collection.immutable.Stream.foldLeft(Stream.scala:549)
	at gwen.eval.GwenLauncher.executeFeatureUnitsSequential(GwenLauncher.scala:139)
	at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:99)
	at gwen.eval.GwenLauncher.run(GwenLauncher.scala:61)
	at gwen.eval.GwenApp.run(GwenApp.scala:55)
	at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
	at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at gwen.eval.GwenApp.main(GwenApp.scala:26)
	at gwen.web.WebInterpreter.main(WebIntepreter.scala)
Caused by: gwen.errors.package$ScriptException: Failed to execute JavaScript: !!$('h2')
	at gwen.errors.package$.javaScriptError(errors.scala:68)
	at gwen.web.WebContext.$anonfun$executeJS$1(WebContext.scala:222)
	at gwen.web.WebContext.$anonfun$withWebDriver$3(WebContext.scala:77)
	at gwen.web.DriverManager.withWebDriver(DriverManager.scala:90)
	at gwen.web.WebContext.$anonfun$withWebDriver$2(WebContext.scala:76)
	at gwen.eval.Evaluatable.evaluate(Evaluatable.scala:32)
	at gwen.eval.Evaluatable.evaluate$(Evaluatable.scala:32)
	at gwen.eval.EnvContext.evaluate(EnvContext.scala:46)
	at gwen.web.WebContext.withWebDriver(WebContext.scala:76)
	at gwen.web.WebContext.executeJS(WebContext.scala:210)
	at gwen.web.WebEnvContext.evaluateJS(WebEnvContext.scala:288)
	at gwen.eval.support.ScriptSupport.evaluateJSPredicate(ScriptSupport.scala:44)
	at gwen.eval.support.ScriptSupport.evaluateJSPredicate$(ScriptSupport.scala:43)
	at gwen.eval.EnvContext.evaluateJSPredicate(EnvContext.scala:46)
	at gwen.web.WebEngine.$anonfun$evaluate$9(WebEngine.scala:203)
	at gwen.web.WebContext.$anonfun$waitUntil$2(WebContext.scala:250)
	at gwen.web.WebContext.$anonfun$waitUntil$2$adapted(WebContext.scala:250)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	at gwen.web.WebContext.$anonfun$waitUntil$1(WebContext.scala:250)
	at gwen.web.WebContext.$anonfun$waitUntil$1$adapted(WebContext.scala:248)
	at gwen.web.WebContext.$anonfun$withWebDriver$3(WebContext.scala:77)
	at gwen.web.DriverManager.withWebDriver(DriverManager.scala:90)
	at gwen.web.WebContext.$anonfun$withWebDriver$2(WebContext.scala:76)
	at gwen.eval.Evaluatable.evaluate(Evaluatable.scala:32)
	at gwen.eval.Evaluatable.evaluate$(Evaluatable.scala:32)
	at gwen.eval.EnvContext.evaluate(EnvContext.scala:46)
	at gwen.web.WebContext.withWebDriver(WebContext.scala:76)
	at gwen.web.WebContext.waitUntil(WebContext.scala:248)
	at gwen.web.WebContext.waitUntil(WebContext.scala:236)
	at gwen.web.WebEngine.evaluate(WebEngine.scala:203)
	at gwen.web.WebEngine.evaluate$(WebEngine.scala:150)
	at gwen.web.WebInterpreter.evaluate(WebIntepreter.scala:27)
	at gwen.web.WebInterpreter.evaluate(WebIntepreter.scala:27)
	at gwen.eval.EvalEngine.$anonfun$evaluateStep$8(EvalEngine.scala:162)
	at gwen.eval.EvalEngine.$anonfun$evaluateStep$8$adapted(EvalEngine.scala:160)
	at gwen.Predefs$Kestrel$.tap$extension(Predefs.scala:49)
	at gwen.eval.EvalEngine.$anonfun$evaluateStep$7(EvalEngine.scala:160)
	at gwen.eval.EvalEngine.$anonfun$doEvaluate$1(EvalEngine.scala:214)
	at scala.util.Try$.apply(Try.scala:213)
	at gwen.eval.EvalEngine.doEvaluate(EvalEngine.scala:214)
	... 56 more
Caused by: org.openqa.selenium.JavascriptException: javascript error: $ is not defined
  (Session info: chrome=75.0.3770.142)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Sergios-MBP-2', ip: '192.168.168.61', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 75.0.3770.142, chrome: {chromedriverVersion: 75.0.3770.140 (2d9f97485c7b..., userDataDir: /var/folders/fh/zfdmsy3d7z3...}, goog:chromeOptions: {debuggerAddress: localhost:54957}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 02b1e5ef8095cd036a4b8842d0fb8ec3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at gwen.web.WebContext.$anonfun$executeJS$1(WebContext.scala:212)
	... 94 more
ERROR - [1s 174ms] Failed Step: Given I wait until the heading is displayed
ERROR - [1s 174ms] Failed Step: Given I am on the challenge completed page
ERROR - [1s 174ms] Failed Scenario: Verify robot completion
INFO - Evaluated feature: Complete the floodio challenge (gwen-web-demo) [file: features/1_CALC-4806.feature]
ERROR - [1s 178ms] Failed feature: Complete the floodio challenge (gwen-web-demo)
INFO - Slideshow feature detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/1_CALC-4806/1_CALC-4806.feature.slideshow.html
INFO - HTML feature detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/1_CALC-4806/1_CALC-4806.feature.html
INFO - HTML meta detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/1_CALC-4806/meta/0001-Google.meta.html
INFO - HTML meta detail report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/features/1_CALC-4806/meta/0002-FloodIO.meta.html
INFO - HTML feature summary report generated: /Users/smsf/exps/gwen-workspace/target/reports/html/feature-summary.html
INFO -
INFO - [1s 178ms] Failed [:(], [493ms] Overhead, [1s 675ms] Elapsed, Started: Mon Jul 29 17:17:31 WEST 2019, Finished: Mon Jul 29 17:17:32 WEST 2019
INFO -
INFO - Closing environment context
INFO - Closing browser session

2 features: Passed 0, Failed 2, Sustained 0, Skipped 0, Pending 0
9 scenarios: Passed 0, Failed 2, Sustained 0, Skipped 7, Pending 0
29 steps: Passed 2, Failed 2, Sustained 0, Skipped 25, Pending 0

[11s 540ms] Failed [:(]
[204ms] Overhead
[11s 744ms] Elapsed, Started: Mon Jul 29 17:17:21 WEST 2019, Finished: Mon Jul 29 17:17:32 WEST 2019
`

**Comment by bitcoder** [comment]
let me investigate this further on my side

**Comment by bitcoder** [comment]
the problem was that I was using slightly modified .feature files which contain the scenarios (in the floodio example) in a different order.. and in that case, it won't work as the .feature file is assuming that they will be executed by order within the .feature file. 
I'd recommend though to not have dependent scenarios, it's more clean and will allow you to run them in any order or just a subset of them
